/**
 * bitwise. - Canonical Site Data Store
 * Auto-generated by Executive Dashboard on 9/8/2026, 12:11:08 AM
 */

window.BITWISE_SITE_DATA = {
  "version": "1.0.0",
  "updatedAt": "2026-09-07T18:41:08.473Z",
  "cms": {
    "hero-tagline": "YOU THINK. WE MAKE.",
    "hero-subtitle": "Creative studio crafting high-impact photography, videography, and graphic design for forward-thinking brands.",
    "hero-cta-text": "Start a Project",
    "hero-cta-secondary": "View Our Work",
    "nav-cta-text": "Start a Project",
    "mobile-cta-text": "Start a Project",
    "services-title": "What We Offer",
    "services-subtitle": "We craft visual stories through the lens, on the screen, and across every medium.",
    "service-1-name": "Photography",
    "service-1-desc": "Editorial, product, portrait, and event photography tailored to your brand.",
    "service-2-name": "Videography",
    "service-2-desc": "Brand films, event coverage, and motion content that captures attention.",
    "service-3-name": "Graphic Design",
    "service-3-desc": "Brand identity, marketing collateral, social media assets, and visual systems.",
    "team-title": "The Founders",
    "team-subtitle": "Three visionary creators crafting the next generation of visual experiences.",
    "founder-1-depth": "AAQIB",
    "founder-1-name": "Aaqib Nazran",
    "founder-1-role": "Co-Founder Â· Creative Director",
    "founder-1-bio": "Shapes the studio's aesthetic compass, brand worldbuilding, and executive visual storytelling across global productions.",
    "founder-2-depth": "RUHAIM",
    "founder-2-name": "Ruhaim Riyaz",
    "founder-2-role": "Co-Founder Â· Lead Cinematographer",
    "founder-2-bio": "Master of motion, lighting, and camera choreography. Crafts cinematic brand films that balance technical precision with emotion.",
    "founder-3-depth": "ANEEQ",
    "founder-3-name": "Aneeq Ahmed",
    "founder-3-role": "Co-Founder Â· Head of Production",
    "founder-3-bio": "Spearheads high-precision production architecture, executive delivery, and cross-media design execution for studio projects.",
    "photo-title": "Photography",
    "photo-subtitle": "Selected work from our editorial and brand photography projects.",
    "design-title": "Graphic Design",
    "design-subtitle": "Brand identities, visual systems, and creative direction.",
    "video-title": "We also create films.",
    "video-desc": "From brand films to event coverage, our videography captures the motion and emotion behind your story.",
    "video-cta-text": "Discuss Your Project",
    "faq-title": "Frequently Asked Questions",
    "faq-q1": "What services does bitwise. offer?",
    "faq-a1": "We specialize in photography, videography, and graphic design. From brand shoots to full visual identities, we cover every creative need for your business or personal project.",
    "faq-q2": "How long does a typical project take?",
    "faq-a2": "Timelines vary by scope. A single photo session can be delivered within a week, while full brand identity projects typically run 3 to 6 weeks. We will discuss timelines upfront during our initial consultation.",
    "faq-q3": "Do you travel for shoots?",
    "faq-a3": "Yes. We are available for both local and destination shoots. Travel costs will be discussed and agreed upon before the project begins.",
    "faq-q4": "What is your pricing structure?",
    "faq-a4": "Pricing depends on the project scope and deliverables. We provide a detailed quote after understanding your requirements during our first conversation. No hidden fees.",
    "faq-q5": "Can I request revisions?",
    "faq-a5": "Absolutely. Our packages include a set number of revision rounds. Additional revisions can be arranged at an agreed rate. We want you to be fully satisfied with the final result.",
    "faq-q6": "How do I get started?",
    "faq-a6": "Simply fill out our contact form or send us an email. We will schedule a brief call to discuss your project, timeline, and budget. From there, we handle the rest.",
    "contact-title": "Start a Project",
    "contact-subtitle": "Tell us about your vision. We will get back to you promptly.",
    "contact-heading": "Get in Touch",
    "contact-desc": "Whether you need a single session or a full creative campaign, we are ready to listen.",
    "contact-email": "bitwise1216@gmail.com",
    "contact-phone": "+94 075 215 4499",
    "contact-address": "Global Atelier",
    "response-time": "We typically respond within 24 hours",
    "contact-card-title": "Launch an Inquiry",
    "contact-card-desc": "Tell us about your brand vision, target timeline, and deliverables. Fill out our official project inquiry form and our team will get back to you within 24 hours.",
    "contact-btn-text": "Start Project Inquiry",
    "footer-tagline": "YOU THINK. WE MAKE.",
    "footer-desc": "Creative studio crafting photography, videography, and graphic design for brands and individuals.",
    "footer-copy": "&copy; 2026 bitwise. All rights reserved.",
    "privacy-title": "Privacy Policy",
    "privacy-updated": "Last updated: September 2026",
    "privacy-content": "<h2>1. Information We Collect</h2>\n<p>When you contact us through our website, we collect only the information you voluntarily provide:</p>\n<ul>\n  <li>Full name</li>\n  <li>Email address</li>\n  <li>The contents of your message</li>\n</ul>\n<p>We do not collect any additional personal data. We do not use tracking cookies or third-party analytics by default.</p>\n\n<h2>2. How We Use Your Information</h2>\n<p>Your information is used solely to respond to your inquiry, discuss potential projects, and provide requested services.</p>\n<p>We will never sell, rent, or share your personal information with third parties for marketing purposes.</p>\n\n<h2>3. Cookies</h2>\n<p>This website uses only essential cookies required for basic functionality. We do not use advertising cookies or tracking pixels.</p>\n\n<h2>4. Data Storage and Security</h2>\n<p>Contact form submissions are processed and stored securely. We implement reasonable security measures to protect your data against unauthorized access, alteration, or destruction.</p>\n\n<h2>5. Contact</h2>\n<p>If you have any questions about this privacy policy, please contact us at <a href=\"mailto:bitwise1216@gmail.com\">bitwise1216@gmail.com</a>.</p>",
    "terms-title": "Terms & Conditions",
    "terms-updated": "Last updated: September 2026",
    "terms-content": "<h2>1. Agreement to Terms</h2>\n<p>By accessing or using the bitwise. website and engaging our services, you agree to be bound by these Terms and Conditions.</p>\n\n<h2>2. Services</h2>\n<p>bitwise. provides professional photography, videography, and graphic design services. The specific scope, deliverables, timeline, and pricing for each project will be discussed and agreed upon before work begins.</p>\n\n<h2>3. Booking and Payment</h2>\n<ul>\n  <li>A project begins once a written agreement (via email or contract) is confirmed by both parties.</li>\n  <li>Payment terms, including any deposit requirements, will be outlined in the project proposal.</li>\n  <li>Full payment is due according to the agreed schedule.</li>\n</ul>\n\n<h2>4. Intellectual Property</h2>\n<ul>\n  <li>Upon full payment, the client receives a license to use the final deliverables for the agreed purposes.</li>\n  <li>bitwise. retains the right to use completed work in portfolios, marketing, and case studies unless otherwise agreed in writing.</li>\n</ul>\n\n<h2>5. Contact</h2>\n<p>For any questions regarding these Terms and Conditions, please contact us at <a href=\"mailto:bitwise1216@gmail.com\">bitwise1216@gmail.com</a>.</p>",
    "refund-title": "Refund Policy",
    "refund-updated": "Last updated: September 2026",
    "refund-content": "<h2>1. Overview</h2>\n<p>We value your trust and aim to deliver work that exceeds expectations. This policy outlines the terms under which refunds and cancellations are handled for our photography, videography, and graphic design services.</p>\n\n<h2>2. Deposits</h2>\n<p>Most projects require a deposit to secure your booking. Deposits confirm your commitment and allow us to allocate resources for your project.</p>\n\n<h2>3. Cancellation by Client</h2>\n<ul>\n  <li><strong>Before work begins:</strong> If you cancel before any work has started, your deposit will be refunded in full, minus any administrative fees incurred.</li>\n  <li><strong>After work has begun:</strong> If you cancel after work has started, the deposit is non-refundable. Any additional payments will be refunded proportionally based on the work not yet completed.</li>\n  <li><strong>Completed deliverables:</strong> No refund is available for deliverables that have been completed and delivered to you.</li>\n</ul>\n\n<h2>4. Rescheduling</h2>\n<p>Rescheduling requests made at least 7 days before the scheduled session or deadline will be accommodated at no extra charge, subject to our availability.</p>\n\n<h2>5. Contact</h2>\n<p>To request a refund, cancellation, or discuss any billing inquiries, please contact us at <a href=\"mailto:bitwise1216@gmail.com\">bitwise1216@gmail.com</a>.</p>"
  },
  "photos": [
    {
      "id": "photo-3",
      "name": "DSC00168.jpg",
      "span": "standard",
      "alt": "bitwise. Photography - DSC00168",
      "size": "1.3 MB"
    },
    {
      "id": "photo-4",
      "name": "DSC00477.jpg",
      "span": "wide",
      "alt": "bitwise. Photography - DSC00477",
      "size": "1.0 MB"
    },
    {
      "id": "photo-5",
      "name": "DSC00586.jpg",
      "span": "tall",
      "alt": "bitwise. Photography - DSC00586",
      "size": "641 KB"
    },
    {
      "id": "photo-6",
      "name": "DSC00830.jpg",
      "span": "standard",
      "alt": "bitwise. Photography - DSC00830",
      "size": "1.7 MB"
    },
    {
      "id": "photo-1788803241957",
      "name": "DSC01253.jpg",
      "span": "standard",
      "alt": "bitwise. Photography - DSC01253",
      "size": "606 KB"
    },
    {
      "id": "photo-1788803250816",
      "name": "DSC01251.jpg",
      "span": "standard",
      "alt": "bitwise. Photography - DSC01251",
      "size": "587 KB"
    },
    {
      "id": "photo-1788803258170",
      "name": "DSC_0387.jpg",
      "span": "tall",
      "alt": "bitwise. Photography - DSC 0387",
      "size": "563 KB"
    },
    {
      "id": "photo-1788803264937",
      "name": "DSC_0603.jpg",
      "span": "tall",
      "alt": "bitwise. Photography - DSC 0603",
      "size": "506 KB"
    },
    {
      "id": "photo-1788803271099",
      "name": "DSC00768.jpg",
      "span": "tall",
      "alt": "bitwise. Photography - DSC00768",
      "size": "415 KB"
    },
    {
      "id": "photo-1788803283967",
      "name": "DSC00599.jpg",
      "span": "tall",
      "alt": "bitwise. Photography - DSC00599",
      "size": "475 KB"
    },
    {
      "id": "photo-1788803290354",
      "name": "DSC01280.jpg",
      "span": "tall",
      "alt": "bitwise. Photography - DSC01280",
      "size": "470 KB"
    }
  ],
  "designs": [
    {
      "id": "design-1",
      "title": "Brand Architecture",
      "category": "Visual Identity",
      "client": "bitwise. Atelier",
      "description": "Core typographic design system, logo identities, and editorial print collateral.",
      "image": ""
    },
    {
      "id": "design-2",
      "title": "Cinematic Motion Systems",
      "category": "Motion Design",
      "client": "Global Production",
      "description": "Digital screen interfaces, title choreography, and high-framerate dynamic layouts.",
      "image": ""
    },
    {
      "id": "design-3",
      "title": "Architectural Exhibition",
      "category": "Spatial Design",
      "client": "Pavilion Series",
      "description": "Monochrome spatial systems, depth layouts, and digital installation assets.",
      "image": ""
    }
  ],
  "founders": {
    "founder-1-img": "assets/Founders/Aaqib Nazran-cutout.png",
    "founder-2-img": "assets/Founders/Ruhaim Riyaz-cutout.png",
    "founder-3-img": "assets/Founders/Aneeq Ahmed-cutout.png"
  }
};
